export const majorsData = [
  { name: 'Computer Science' },
  { name: 'Software Engineering' },
  { name: 'Artificial Intelligence & Machine Learning' },
  { name: 'Data Science' },
  { name: 'Computer Engineering' },
  { name: 'Human–Computer Interaction (HCI)' },
  { name: 'Robotics & Automation' },
  { name: 'Computational Science' },
  { name: 'Game Development' },
  { name: 'Cloud Computing' },
  { name: 'Digital Business Management' },
  { name: 'E-Commerce' },
  { name: 'Business Information Systems' },
  { name: 'Digital Marketing' },
  { name: 'Innovation & Entrepreneurship' },
  { name: 'FinTech (Financial Technology)' },
  { name: 'Business Analytics' },
  { name: 'Management Information Systems (MIS)' },
  { name: 'Technology Management' },
  { name: 'Supply Chain & Digital Operations' },
  { name: 'Information Technology (IT)' },
  { name: 'Network Engineering' },
  { name: 'Computer Networks & Systems' },
  { name: 'Telecommunications Engineering' },
  { name: 'Wireless & Mobile Computing' },
  { name: 'Internet of Things (IoT)' },
  { name: 'Cloud Networking' },
  { name: 'Communication Systems' },
  { name: 'Broadband & Optical Communication' },
  { name: 'Satellite Communication' },
  { name: 'Cybersecurity' },
  { name: 'Information Security' },
  { name: 'Ethical Hacking & Penetration Testing' },
  { name: 'Digital Forensics' },
  { name: 'Cryptography & Network Security' },
  { name: 'Cloud Security' },
  { name: 'Cyber Defense & Threat Intelligence' },
  { name: 'Security & Risk Management' },
  { name: 'Security Operations & Incident Response' },
  { name: 'Governance, Risk, and Compliance (GRC)' },
];
