export const researchFieldsData = [
  { name: 'Artificial Intelligence (AI)' },
  { name: 'Machine Learning (ML)' },
  { name: 'Deep Learning' },
  { name: 'Data Science & Analytics' },
  { name: 'Algorithms & Complexity' },
  { name: 'Programming Languages & Compilers' },
  { name: 'Operating Systems' },
  { name: 'Computer Architecture' },
  { name: 'Databases & Information Systems' },
  { name: 'Big Data' },
  { name: 'Distributed Systems' },
  { name: 'Cloud Computing' },
  { name: 'High Performance Computing (HPC)' },
  { name: 'Internet of Things (IoT)' },
  { name: 'Cybersecurity' },
  { name: 'Network Security' },
  { name: 'Cryptography' },
  { name: 'Blockchain Technology' },
  { name: 'Computer Networks & Communications' },
  { name: 'Robotics' },
  { name: 'Natural Language Processing (NLP)' },
  { name: 'Computer Vision' },
  { name: 'Human–Computer Interaction (HCI)' },
  { name: 'Intelligent Agents & Multi-Agent Systems' },
  { name: 'Software Engineering' },
  { name: 'Web Technologies' },
  { name: 'Mobile Computing' },
  { name: 'Game Development' },
  { name: 'E-learning Technologies' },
  { name: 'Quantum Computing' },
  { name: 'Bioinformatics & Computational Biology' },
  { name: 'Computational Neuroscience' },
  { name: 'Augmented Reality (AR) & Virtual Reality (VR)' },
  { name: 'Ethics in AI & Responsible Computing' },
];
