export const universitiesData = [
  // Universities
  { name: 'American University of Phnom Penh' },
  { name: 'Angkor Khemara University' },
  { name: 'Angkor University' },
  { name: 'Asia Euro University' },
  { name: 'Beltei International University' },
  { name: 'Build Bright University' },
  { name: 'Cambodia Academy Of Digital Technology' },
  { name: 'Cambodia University for Specialties' },
  { name: 'Cambodian Mekong University' },
  { name: 'CamEd Business School' },
  { name: 'Chenla University' },
  { name: 'Dewey International University' },
  { name: 'East Asia Management University' },
  { name: "École Royale d'Administration" },
  { name: 'Human Resources University' },
  { name: 'IIC University of Technology' },
  { name: 'International University' },
  { name: 'Khemarak University' },
  { name: 'Life University, Cambodia' },
  { name: 'Limkokwing University of Creative Technology, Cambodia' },
  { name: 'National Meanchey University' },
  { name: 'National University of Battambang' },
  { name: 'National University of Management' },
  { name: 'Norton University' },
  { name: 'Panha Chiet University' },
  { name: 'Paññāsāstra University of Cambodia' },
  { name: 'Paragon International University' },
  { name: 'Phnom Penh International University' },
  { name: 'Preah Sihanouk Raja Buddhist University' },
  { name: 'Royal Academy of Cambodia' },
  { name: 'Royal University of Agriculture' },
  { name: 'Royal University of Fine Arts' },
  { name: 'Royal University of Law and Economics' },
  { name: 'Royal University of Phnom Penh' },
  { name: 'Svay Rieng University' },
  { name: 'The University of Cambodia' },
  { name: 'Université des Sciences de la Santé' },
  { name: 'University of Management and Economics' },
  { name: 'University of Puthisastra' },
  { name: 'University of Southeast Asia' },
  { name: 'Western University, Cambodia' },

  // Institutes
  { name: 'Institute of Technology of Cambodia' },
  { name: 'Kampong Cham National Institute of Agriculture' },
  { name: 'National Institute of Business' },
  { name: 'National Institute of Education' },
  { name: 'National Polytechnic Institute of Cambodia' },
  { name: 'Prek Leap National Institute of Agriculture' },
  { name: 'Vanda Institute' },
  { name: 'Kirirom Institute of Technology' },
  { name: 'National Institute of Public Health' },
  { name: 'Institute of Foreign Languages (IFL)' },
  { name: 'Institute of Banking and Finance' },
  { name: 'Economics and Finance Institute' },
  { name: 'SETEC Institute' },
  { name: 'Instinct Institute' },

  // Colleges
  { name: 'Royal University of Phnom Penh - College of Social Sciences' },
  { name: 'Royal University of Phnom Penh - College of Science' },
  { name: 'College of Science and Technology (The University of Cambodia)' },
  { name: 'College of Management (The University of Cambodia)' },
  { name: 'College of Media and Communications (The University of Cambodia)' },
  { name: 'College of Education (The University of Cambodia)' },
  { name: 'College of Law (The University of Cambodia)' },
  { name: 'College of Medicine and Health Sciences (The University of Cambodia)' },
];
